server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/mime.types;

    location / {
        try_files $uri $uri/ /index.html =404;
    }

    # Cache de arquivos estáticos da framework
    location ~* \.(css|js|png|jpg|jpeg|gif|ico|woff|woff2|ttf|eot|wasm)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    # Evita cache do index.html, blazor.boot.json e appsettings.json para refletir novas versões
    location ~* (index\.html|blazor\.boot\.json|appsettings\.json)$ {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}
